# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Antistatic < Formula
  desc "CLI for Antistatic Exchange"
  homepage "https://antistatic.exchange"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/finnhambly/antistatic-cli/releases/download/v0.1.2/antistatic_0.1.2_darwin_amd64.tar.gz"
      sha256 "2967cf270bdf51fa0f03d37beda7f04925a44ddf28db59dac10e544ca10a62fd"

      define_method(:install) do
        bin.install "antistatic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/finnhambly/antistatic-cli/releases/download/v0.1.2/antistatic_0.1.2_darwin_arm64.tar.gz"
      sha256 "c33ed7430446b0c1c6f0a70d61924d99e25bb333f15ddce1640a10398d4cd848"

      define_method(:install) do
        bin.install "antistatic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/finnhambly/antistatic-cli/releases/download/v0.1.2/antistatic_0.1.2_linux_amd64.tar.gz"
      sha256 "e9a04cd1c8710d35f34b64c7ca5587b64e2ddc7c552e9ff25d151eb76c8327ad"
      define_method(:install) do
        bin.install "antistatic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/finnhambly/antistatic-cli/releases/download/v0.1.2/antistatic_0.1.2_linux_arm64.tar.gz"
      sha256 "7e9e2bf11224bd174c218a1e67d3476957ee207fb4797414efe2378f528b09c6"
      define_method(:install) do
        bin.install "antistatic"
      end
    end
  end
end
