# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Antistatic < Formula
  desc "CLI for Antistatic Exchange"
  homepage "https://antistatic.exchange"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/finnhambly/antistatic-cli/releases/download/v0.1.1/antistatic_0.1.1_darwin_amd64.tar.gz"
      sha256 "195c18f3601a30547b732c9e5b3ed6823c43f5a17c560a3b9be7e658de54252d"

      define_method(:install) do
        bin.install "antistatic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/finnhambly/antistatic-cli/releases/download/v0.1.1/antistatic_0.1.1_darwin_arm64.tar.gz"
      sha256 "51dffbac61a7c154bb586ba7c70555b2a84f07ad8e809825c296e9b68bd6d517"

      define_method(:install) do
        bin.install "antistatic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/finnhambly/antistatic-cli/releases/download/v0.1.1/antistatic_0.1.1_linux_amd64.tar.gz"
      sha256 "39a6cac524578a8c84771f9fce6df78428e89d7baadc50b4b04b53df0c553899"
      define_method(:install) do
        bin.install "antistatic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/finnhambly/antistatic-cli/releases/download/v0.1.1/antistatic_0.1.1_linux_arm64.tar.gz"
      sha256 "a567836b28dbdfd35b29b66f2d7829e0964cddfe56ff1670d546829b4b3bc517"
      define_method(:install) do
        bin.install "antistatic"
      end
    end
  end
end
